/**
	Generated by sails-inverse-model
	Date:Wed Feb 13 2019 23:28:27 GMT+0100 (Paris, Madrid)
*/

module.exports = {
    attributes: {
        id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        user:{
            model:'user',
            unique: true
          },
        promo: {
            type: "string",
            columnType: "varchar",
            maxLength: 4
        },
        birthday: {
            type: "string",
            columnType: "date"
        },
        associations: {
            collection: 'association',
            via: 'adherants'
          }
    }
};