/**
	Generated by sails-inverse-model
	Date:Wed Feb 13 2019 23:28:27 GMT+0100 (Paris, Madrid)
*/

module.exports = {
    attributes: {
        id: {
            type: 'number',
            autoIncrement: true
         },
        name: {
            type: "string",
            columnType: "varchar",
            maxLength: 50,
            unique: true,
            required: true
        },
        place: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        schedule: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        description: {
            type: "string",
            columnType: "longtext"
        },
        user: {
            model: 'user',
            unique: true
        },
        adherants: {
            collection: 'adherant',
            via: 'associations'
        }

    }
};