/**
	Generated by sails-inverse-model
	Date:Wed Feb 13 2019 23:28:27 GMT+0100 (Paris, Madrid)
*/

module.exports = {
    attributes: {
        id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        username: {
            type: "string",
            columnType: "varchar",
            maxLength: 180,
            required: true
        },
        username_canonical: {
            type: "string",
            columnType: "varchar",
            maxLength: 180,
            unique: true,
            required: true
        },
        email: {
            type: "string",
            columnType: "varchar",
            maxLength: 180,
            required: true
        },
        email_canonical: {
            type: "string",
            columnType: "varchar",
            maxLength: 180,
            unique: true,
            required: true
        },
        enabled: {
            type: "number",
            columnType: "tinyint",
            isInteger: true,
            required: true
        },
        salt: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        password: {
            type: "string",
            columnType: "varchar",
            maxLength: 255,
            required: true
        },
        last_login: {
            type: "string",
            columnType: "datetime"
        },
        confirmation_token: {
            type: "string",
            columnType: "varchar",
            maxLength: 180,
            unique: true
        },
        password_requested_at: {
            type: "string",
            columnType: "datetime"
        },
        roles: {
            type: "string",
            columnType: "longtext",
            required: true
        },
        name: {
            type: "string",
            columnType: "varchar",
            maxLength: 255,
            required: true
        },
        surname: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        picture: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        myDate: {
            type: "string",
            columnType: "datetime",
            defaultsTo: "CURRENT_TIMESTAMP"
        },
        association: {
            collection:'association',
            via: 'user'
          },
        adherant: {
            collection:'adherant',
            via: 'user'
          },
          tags: {
            collection: 'tag',
            via: 'users'
          },
          commentaires: {
            collection: 'commentaire',
            via: 'users'
          }
    }
};